### ISSUE TITLE
I'm getting an error why building docker image

### ISSUE THREAD

**Issue by Dduvacher** [Skillz4Killz/Discordeno-bot-template#48]
First when I run `docker build -t my-image .`
I get an error at STEP 5 it look likes docker can't find cache file
``` Sending build context to Docker daemon  265.7kB
Step 1/8 : FROM hayd/alpine-deno:latest
 ---> c2f9f097bdcf
Step 2/8 : WORKDIR /bot
 ---> Using cache
 ---> 98b1f76e85f3
Step 3/8 : USER deno
 ---> Using cache
 ---> fab4991490ce
Step 4/8 : COPY deps.ts .
 ---> Using cache
 ---> 156b550d4c6d
Step 5/8 : RUN deno cache deps.ts
 ---> Running in 1e2b69918886
Download https://deno.land/std@0.67.0/async/delay.ts
Download https://deno.land/x/sabr@1.1.0/mod.ts
Download https://deno.land/x/discordeno@9.0.15/src/module/client.ts
error: Cannot resolve module "file:///bot/cache.ts" from "file:///bot/deps.ts"
    at file:///bot/deps.ts:5:0
The command '/bin/sh -c deno cache deps.ts' returned a non-zero code: 1
```
This error disappear if I replace `COPY deps.ts .` by `COPY . .`
If I do I get a another error:
```
Sending build context to Docker daemon  265.7kB
Step 1/8 : FROM hayd/alpine-deno:latest
 ---> c2f9f097bdcf
Step 2/8 : WORKDIR /bot
 ---> Using cache
 ---> 98b1f76e85f3
Step 3/8 : USER deno
 ---> Using cache
 ---> fab4991490ce
Step 4/8 : COPY . .
 ---> 680605442c38
Step 5/8 : RUN deno cache deps.ts
 ---> Running in 8d21e6bc57e9
Download https://deno.land/std@0.67.0/fmt/colors.ts
Download https://deno.land/x/discordeno@9.0.15/mod.ts
...
...
...
Check file:///bot/deps.ts
Removing intermediate container 8d21e6bc57e9
 ---> 28f758c4c7b2
Step 6/8 : ADD . .
 ---> bd181ebaae70
Step 7/8 : RUN deno cache mod.ts
 ---> Running in fcb5f848e947
error: read access to "/bot/src/database/database.ts", run again with the --allow-read flag
The command '/bin/sh -c deno cache mod.ts' returned a non-zero code: 1
```
I think it's because of the `await import("./src/database/database.ts");` on mod.ts file
I'm sorry I'm not really comfortable with Docker, and I don't know if you can help me but if you do It will be awesome.

**Comment by ayntee** [comment]
#49

**Comment by ayntee** [comment]
Sabr requires allow write permissions to write the JSON file.

```Dockerfile
CMD ["run", "--allow-net", "--allow-read", "--allow-write", "./mod.ts"]
```

**Comment by Skillz4Killz** [comment]
Probably should add all the flags the bot needs like nocheck and stuff

**Comment by Skillz4Killz** [comment]
And also step 7 perms

**Comment by Dduvacher** [comment]
You're Pull request solved the first issue.
I'm still in trouble with the second one ...
If I run `deno cache mod.ts` in my console everything fine
but the line (STEP 7)`RUN deno cache mod.ts` tell me 
```
error: read access to "/bot/src/database/database.ts", run again with the --allow-read flag
The command '/bin/sh -c deno cache mod.ts' returned a non-zero code: 1
```
I don't understand because there is no option --allow-read  for deno cache...
(I've had the --allow-write and --no-check for the last STEP)

**Comment by ayntee** [comment]
> You're Pull request solved the first issue.
> I'm still in trouble with the second one ...
> If I run `deno cache mod.ts` in my console everything fine
> but the line (STEP 7)`RUN deno cache mod.ts` tell me
> 
> ```
> error: read access to "/bot/src/database/database.ts", run again with the --allow-read flag
> The command '/bin/sh -c deno cache mod.ts' returned a non-zero code: 1
> ```
> 
> I don't understand because there is no option --allow-read for deno cache...
> (I've had the --allow-write and --no-check for the last STEP)

https://github.com/Skillz4Killz/Discordeno-bot-template/pull/49#issuecomment-723401422

**Comment by ayntee** [comment]
Closing this issue. This has been solved in newer versions of Deno.

**Comment by Dduvacher** [comment]
Is it working for you ? I've upgrade my Deno still the same error ...

**Comment by Dduvacher** [comment]
Oh it's working if i change my docker image with hayd/deno:latest instead of hayd/alpine-deno:latest

**Comment by Skillz4Killz** [comment]
Could you please send a PR fixing it if you found a fix
